In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv("CKD.csv")

print("Rows :", dataset.shape[0])
print("Columns :", dataset.shape[1])

dataset.head()

Rows : 399
Columns : 25

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [28]:
dataset = pd.get_dummies(dataset, drop_first=True)

dataset.head()

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,False,False,False,False,False,False,True,True,False,True
1,3,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,False,False,False,False,False,True,False,False,True
2,4,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,False,False,False,False,False,True,False,False,True
3,5,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,False,False,False,False,False,True,False,True,True
4,5,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,False,False,False,False,False,True,False,False,True

In [30]:
indep = dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e',
                 'rbc_normal', 'pc_normal', 'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]

dep = dataset['classification_yes']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    indep,
    dep,
    test_size=1/3,
    random_state=0
)

### SVM

In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

results = []

from sklearn.svm import SVC

classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("SVM")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["SVM", acc])

SVM
[[ 0 51]
 [ 0 82]]
              precision    recall  f1-score   support

       False       0.00      0.00      0.00        51
        True       0.62      1.00      0.76        82

    accuracy                           0.62       133
   macro avg       0.31      0.50      0.38       133
weighted avg       0.38      0.62      0.47       133

Accuracy : 0.6165413533834586

c:\Users\Paul\anaconda3\envs\productqa-env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Paul\anaconda3\envs\productqa-env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Paul\anaconda3\envs\productqa-env\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Random Forest

In [17]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(
    n_estimators=10,
    criterion='entropy',
    random_state=0
)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Random Forest")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["Random Forest", acc])

Random Forest
[[50  1]
 [ 1 81]]
              precision    recall  f1-score   support

       False       0.98      0.98      0.98        51
        True       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

Accuracy : 0.9849624060150376

### Decision Tree

In [18]:
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(
    criterion='entropy',
    random_state=0
)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Decision Tree")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["Decision Tree", acc])

Decision Tree
[[49  2]
 [ 8 74]]
              precision    recall  f1-score   support

       False       0.86      0.96      0.91        51
        True       0.97      0.90      0.94        82

    accuracy                           0.92       133
   macro avg       0.92      0.93      0.92       133
weighted avg       0.93      0.92      0.93       133

Accuracy : 0.924812030075188

### Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(random_state=0)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Logistic Regression")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["Logistic Regression", acc])

Logistic Regression
[[48  3]
 [ 5 77]]
              precision    recall  f1-score   support

       False       0.91      0.94      0.92        51
        True       0.96      0.94      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.94      0.94       133
weighted avg       0.94      0.94      0.94       133

Accuracy : 0.9398496240601504

c:\Users\Paul\anaconda3\envs\productqa-env\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### KNN

In [20]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(
    n_neighbors=7,
    metric='minkowski',
    p=2
)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("KNN")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["KNN", acc])

KNN
[[40 11]
 [30 52]]
              precision    recall  f1-score   support

       False       0.57      0.78      0.66        51
        True       0.83      0.63      0.72        82

    accuracy                           0.69       133
   macro avg       0.70      0.71      0.69       133
weighted avg       0.73      0.69      0.70       133

Accuracy : 0.6917293233082706

### GaussianNB

In [21]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("GaussianNB")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["GaussianNB", acc])

GaussianNB
[[51  0]
 [ 3 79]]
              precision    recall  f1-score   support

       False       0.94      1.00      0.97        51
        True       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

Accuracy : 0.9774436090225563

### MultinomialNB

In [31]:
from sklearn.naive_bayes import MultinomialNB

classifier = MultinomialNB()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("MultinomialNB")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["MultinomialNB", acc])

MultinomialNB
[[50  1]
 [23 59]]
              precision    recall  f1-score   support

       False       0.68      0.98      0.81        51
        True       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

Accuracy : 0.8195488721804511

### BernoulliNB

In [32]:
from sklearn.naive_bayes import BernoulliNB

classifier = BernoulliNB()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("BernoulliNB")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["BernoulliNB", acc])

BernoulliNB
[[51  0]
 [ 8 74]]
              precision    recall  f1-score   support

       False       0.86      1.00      0.93        51
        True       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

Accuracy : 0.9398496240601504

### ComplementNB

In [33]:
from sklearn.naive_bayes import ComplementNB

classifier = ComplementNB()

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("ComplementNB")

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

acc = accuracy_score(y_test, y_pred)
print("Accuracy :", acc)

results.append(["ComplementNB", acc])

ComplementNB
[[50  1]
 [23 59]]
              precision    recall  f1-score   support

       False       0.68      0.98      0.81        51
        True       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

Accuracy : 0.8195488721804511

## OUTPUT

In [34]:
result_df = pd.DataFrame(
    results,
    columns=["Algorithm", "Accuracy"]
)

result_df.sort_values(
    by="Accuracy",
    ascending=False
)

             Algorithm  Accuracy
1        Random Forest  0.984962
5           GaussianNB  0.977444
7          BernoulliNB  0.939850
3  Logistic Regression  0.939850
2        Decision Tree  0.924812
8         ComplementNB  0.819549
6        MultinomialNB  0.819549
4                  KNN  0.691729
0                  SVM  0.616541